default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: todo_list_kryukov_development

test:
  <<: *default
  database: todo_list_kryukov_test

production:
  <<: *default
  database: todo_list_kryukov_production
  username: todo_list_kryukov
  password: <%= ENV['TODO_LIST_KRYUKOV_DATABASE_PASSWORD'] %>
